language: python
sudo: required
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "sudo apt-get update ; sudo apt-get install -y fortune cowsay"
script: "make && [ -f gfortunes -a -f gfortunes.dat ] && ./tellfortune.sh"
